parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    experimentalObjectRestSpread: true
  env:
    es6: true
  extends:
    - standard
  files:
    - patterns:
        - '**/*.test.js'
        - '**/*.spec.js'
      env:
        jest: true
    - patterns:
        - '**/*.jsx'
      env:
        browser: true
        node: true
  rules:
    no-var: true
    prefer-const: true
