
language: node_js

sudo: required

node_js:
  - '6'

before_script:
  - chmod -R +x sh
  - source ./sh/travis-ci/before-script.sh

script:
  - npm test

before_deploy:
  - source ./sh/travis-ci/before-deploy.sh

deploy:
  provider: script
  script: ./sh/travis-ci/deploy.sh
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - source ./sh/travis-ci/after-deploy.sh
