
language: node_js

sudo: required

node_js:
  - '8'

env:
  - COVERALLS=true

cache:
  directories:
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.node-gyp
    - $HOME/.node_libraries
    - $HOME/node_modules
    - node_modules

before_script:
  - chmod -R +x sh
  - source ./sh/travis-ci/before-script.sh

script:
  - npm test

before_deploy:
  - source ./sh/travis-ci/before-deploy.sh

deploy:
  provider: script
  script: ./sh/travis-ci/deploy.sh
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - source ./sh/travis-ci/after-deploy.sh

branches:
  except:
    - gh-pages
