
language: node_js

sudo: required

node_js:
  - '6'

before_script:
  - chmod -R +x sh
  - [ -z TRAVIS_TAG ] && BUILD_MODE=Debug || BUILD_MODE=Release
  - export BUILD_MODE
  - export GIT_REPO_TAG=$TRAVIS_TAG

script:
  - npm test

before_deploy:
  - source ./sh/deploy/travis-ci/before.sh

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_OAUTH
  skip_cleanup: true
  file_glob: true
  file: $(./sh/deploy/travis-ci/directory.sh)/*
  on:
    tags: true

after_deploy:
  - source ./sh/deploy/travis-ci/after.sh
