
language: node_js

sudo: required

node_js:
  - '6'

before_script:
  - source ./sh/travis-ci/before-script.sh

script:
  - npm test

before_deploy:
  - source ./sh/travis-ci/before-deploy.sh

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_OAUTH
  skip_cleanup: true
  file_glob: true
  file: $(./sh/deploy/travis-ci/directory.sh)/*
  on:
    tags: true

after_deploy:
  - source ./sh/travis-ci/after-deploy.sh
