
language: node_js

sudo: required

node_js:
  - '6'

before_script:
  - chmod -R +x sh

before_deploy:
  - chmod -R +x sh
  - source ./sh/deploy/travis-ci/before.sh

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_OAUTH
  skip_cleanup: true
  file_glob: true
  file: $(./sh/deploy/travis-ci/directory.sh)/*
  on:
    tags: true

after_deploy:
  - source ./sh/deploy/travis-ci/after.sh
