branches:
  except:
    - gh-pages

environment:
  matrix:
    - nodejs_version: 8

cache:
  - '%USERPROFILE%\.nuget\packages'
  - '%LOCALAPPDATA%\Yarn'
  - node_modules

image: Visual Studio 2015

clone_folder: C:\Projects\Main

clone_depth: 1

install:
  - cmd: echo "Repo URL" && git remote get-url origin
  - ps: Install-Product node $env:nodejs_version
  - cmd: yarn

build_script:
  - cmd: echo "NodeJS version" && node --version
  - cmd: echo "YARN version" && yarn --version
  - cmd: echo "Test" && yarn test

artifacts:
  - path: dist\*.*

deploy:
  - provider: GitHub
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
